### ISSUE TITLE
Skill dice rolls

### ISSUE THREAD

**Issue by Rafynwolf** [VacantFanatic/SLAfoundry#51]
When I roll a skill roll the results do not appear on the activity log.   3D dice for Dice so nice also do not roll.   If I refresh the page the results appear.   If I roll a attribute roll then the dice do roll and the results appear.  
I am using Foundry hosted on forge using Norton Security Web Browser.

**Comment by VacantFanatic** [comment]
Could you also include which version and any modules you're using?

![image](https://github.com/VacantFanatic/SLAfoundry/assets/5420476/0d557438-33b8-4ed5-9399-074d6824ff0f)

**Comment by Rafynwolf** [comment]
![image](https://github.com/VacantFanatic/SLAfoundry/assets/156451965/1d459c82-f77f-49e7-bd54-1ebef6b40c1e)

Modules loaded - Dice so nice (4.6.8)  and Dice Tray (1.4.2)

**Comment by Rafynwolf** [comment]
Also just noticed that when I refresh and the roll results appear I see the below.   As polearms is rated at 0  should this not be a single dice plus str.  stat?  This looks to be 2 dice  + str.

![image](https://github.com/VacantFanatic/SLAfoundry/assets/156451965/ce0b06d5-9b8c-4f3a-82dc-a5854fa27027)

**Comment by VacantFanatic** [comment]
Ok so: 
- Dice so nice is definitely the culprit for the first one.  I'm currently building "roll cards" that will allow damage rolls, etc. from the attack result roll card.  I'll also be implementing a pop-up for mods + melee dice (attack v defense dice).  When I get to those I'll integrate with DSN

For the # of dice it turns out a skill roll is actually (Success die + a number of dice equal to the skill (zero in this case) + an additional die). I had thought it was just the skill pool as well when I had first set  it up :-)

![image](https://github.com/VacantFanatic/SLAfoundry/assets/5420476/2fe5c490-c4bb-4659-a354-889255c3b8e1)

**Comment by Rafynwolf** [comment]
Thanks.
I can confirm that after deactivating DsN results appear.  
Apologies for mistake on the skill roll.  I read that about 4 times before posting,  and still got it wrong ;o)
I then reread another 3 times after reading your reply.   Yes.   success dice plus skill rank,  + 1.  :o)  

Would it be ok for me to make some suggestions for later enhancements?
If so,  could I suggest the below:
1 - Make Success dice identifiable as separate line in results (minor as in meantime would just say top result was success dice but a nice addition)
2 - leading on from 1,  when integrated with DSN make the success dice to be modified separate from other dice so it can appear as a different colour. 
3 - Allow target number to be added prior to roll, 
4 - leading on from 3 - display results to indicate success/fail and additional successes etc.  

Many thanks.

**Comment by VacantFanatic** [comment]
No worries and please suggest away!
1 - I'm aiming to do something like this when I do the roll card. Have a PNG of a Black die with the total # on one row followed by a white die (dice) PNG on a separate line for the skill dice. (Part of the roll cards mentioned above). 
2 - Agreed I'd like the same to happen in DSN (Black die plus white skill - round two would see those colors customizable)
3 - This one I'm on the fence about.  Ranged rolls make sense.  Melee is more difficult due to the contested nature. For skill rolls as a GM I'm not fond of this. I'd rather ask for the roll and narrate the result.  The player doesn't need to know the DV.
4 - Again this moves the needle to far to the "video game" side IMHO. I'd rather leave it to the GM to determine degree of success and narrate.
