### ISSUE TITLE
Character sheets - unable to view

### ISSUE THREAD

**Issue by Mortium666** [VacantFanatic/SLAfoundry#52]
Updated to 4.40 and now cannot read old character sheets. 
I created a new character sheet and after saving it, I cannot open the character sheet either.
When I did create the new character, I noted that the Ebb Skills I created as items couldn't be dragged into place, and neither could the weapon I created previously.
Foundry v11 Stable
Sla Industries 0.4.40
Active Modules: 0

**Comment by VacantFanatic** [comment]
Unfortunately this is a side effect of data model updates. Currently there are no migration scripts being done (due to the limited time I have to work on this). Migration scripts will be done post 1.0 / out of Beta when the model is less volatile.

I've updated https://github.com/VacantFanatic/SLAfoundry?tab=readme-ov-file#slaindustries-system to make this more clear moving forward.
